export TURTLEBOT3_MODEL=waffle
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
source /opt/ros/humble/setup.bash
source /home/ROS/ros_ws/install/setup.bash
# source /usr/share/colcon_argcomplete/hook/colcon_argcomplete.bash
